Metrics/AbcSize:
  Max: 35

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Layout/CaseIndentation:
  Exclude:
    - 'features/support/helpers/helpers.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'features/support/env.rb'
    - 'features/support/helpers/**/*'
    - 'features/support/pages/**/*'
    - 'features/support/screens/**/*'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'features/support/pages/**/*'
    - 'features/support/screens/**/*'

Style/StringLiterals:
  Exclude:
    - 'features/support/pages/**/*'
    - 'features/support/screens/**/*'

Layout/EmptyLineAfterGuardClause:
  Enabled: false
