local:
  root_url: https://techguide.parkinsons.org.uk/

vercel:
  root_url: https://puk-tech-guide-git-feature-t-7748-cygnet1.vercel.app/
  
qa:
  root_url: https://puk-tech-guide.vercel.app/

production:
  root_url: https://techguide.parkinsons.org.uk/
